/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author eduva
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Controller controller;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        controller = new Controller();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenero = new javax.swing.ButtonGroup();
        btnRelatorios = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JTabbedPane();
        tabCadastro = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        lblGenero = new javax.swing.JLabel();
        btnMasculino = new javax.swing.JRadioButton();
        btnFeminino = new javax.swing.JRadioButton();
        lblVip = new javax.swing.JLabel();
        comboVip = new javax.swing.JComboBox<>();
        btnConsulta = new javax.swing.JButton();
        txtIdade = new javax.swing.JTextField();
        lblVip1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        tabRelatorio = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResultadodosRelatorio = new javax.swing.JTextArea();
        lblTotal = new javax.swing.JLabel();
        btnGerarRelatorio = new javax.swing.JButton();
        lblMulheres = new javax.swing.JLabel();
        lblHomens = new javax.swing.JLabel();
        lblSilver = new javax.swing.JLabel();
        lblGold = new javax.swing.JLabel();
        lblPlatinum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.setToolTipText("");
        tabCadastro.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 505, -1));

        lblNome.setText("NOME");
        tabCadastro.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblCPF.setText("CPF");
        tabCadastro.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tabCadastro.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 505, -1));

        lblGenero.setText("GENERO");
        tabCadastro.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnGenero.add(btnMasculino);
        btnMasculino.setSelected(true);
        btnMasculino.setText("Masculino");
        tabCadastro.add(btnMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 124, -1, -1));

        btnGenero.add(btnFeminino);
        btnFeminino.setText("Feminino");
        tabCadastro.add(btnFeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        lblVip.setText("Idade");
        tabCadastro.add(lblVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 20));

        comboVip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Silver", "Gold", "Platinum" }));
        tabCadastro.add(comboVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 270, -1));

        btnConsulta.setText("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        tabCadastro.add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 100, -1));

        txtIdade.setToolTipText("");
        tabCadastro.add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 50, -1));

        lblVip1.setText("VIP");
        tabCadastro.add(lblVip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, 20));

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        tabCadastro.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 260, 100, -1));

        panelPrincipal.addTab("Cadastro / Consulta", tabCadastro);

        jTextAreaResultadodosRelatorio.setColumns(20);
        jTextAreaResultadodosRelatorio.setRows(5);
        jScrollPane2.setViewportView(jTextAreaResultadodosRelatorio);

        lblTotal.setText("Total: 0000");

        btnGerarRelatorio.setText("Gerar Relatorio");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        lblMulheres.setText("Mulheres: 0000");

        lblHomens.setText("Homens: 0000");

        lblSilver.setText("Silver: 0000");

        lblGold.setText("Gold: 0000");

        lblPlatinum.setText("Platinum: 0000");

        javax.swing.GroupLayout tabRelatorioLayout = new javax.swing.GroupLayout(tabRelatorio);
        tabRelatorio.setLayout(tabRelatorioLayout);
        tabRelatorioLayout.setHorizontalGroup(
            tabRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRelatorioLayout.createSequentialGroup()
                .addGroup(tabRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabRelatorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabRelatorioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(tabRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabRelatorioLayout.createSequentialGroup()
                                .addComponent(lblHomens)
                                .addGap(18, 18, 18)
                                .addComponent(lblMulheres)
                                .addGap(18, 18, 18)
                                .addComponent(lblSilver)
                                .addGap(18, 18, 18)
                                .addComponent(lblGold)
                                .addGap(18, 18, 18)
                                .addComponent(lblPlatinum)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        tabRelatorioLayout.setVerticalGroup(
            tabRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRelatorioLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(tabRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblGold)
                    .addComponent(lblMulheres)
                    .addComponent(lblHomens)
                    .addComponent(lblSilver)
                    .addComponent(lblPlatinum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerarRelatorio)
                .addGap(7, 7, 7))
        );

        panelPrincipal.addTab("Relatorio", tabRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        char genero = btnFeminino.isSelected() ? 'F' : 'M';

        if (controller.validarCampos(txtNome.getText(), txtCPF.getText(), (txtIdade.getText().equals("") ? 0 : Integer.valueOf(txtIdade.getText())))) {
            if (controller.realizarCadastro(txtNome.getText(), txtCPF.getText(), Integer.valueOf(txtIdade.getText()), comboVip.getSelectedItem().toString(), genero)) {
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");

                txtNome.setText("");
                txtCPF.setText("");
                txtIdade.setText("");
                comboVip.getItemAt(0);
                btnMasculino.setSelected(true);

            } else {
                JOptionPane.showMessageDialog(null, "Erro ao realizar o cadastro!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao validar, por favor confira os dados do cadastro!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        ClienteModel cliente = controller.consultaCliente(txtCPF.getText());
        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
        } else {
            txtNome.setText(cliente.getNome());
            txtCPF.setText(cliente.getCpf());
            txtIdade.setText(cliente.getIdade());

            for (int i = 0; i < comboVip.getItemCount(); i++) {
                if (comboVip.getItemAt(i).equals(cliente.getStatus())) {
                    comboVip.setSelectedIndex(i);
                }
            }

            if (cliente.getGenero() == 'F') {
                btnFeminino.setSelected(true);
            } else {
                btnMasculino.setSelected(true);
            }

            JOptionPane.showMessageDialog(null, "Busca realizada com sucesso!");
        }


    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        jTextAreaResultadodosRelatorio.setText(controller.relatorioClientes());
        lblHomens.setText("Homens:" + controller.getPercentualHomem() + "%");
        lblMulheres.setText("Mulheres:" + controller.getPercentualMulher() + "%");
        lblSilver.setText("Silver:" + controller.getSilver() + "%");
        lblGold.setText("Gold:" + controller.getGold() + "%");
        lblPlatinum.setText("Platinum:" + controller.getPlatinum() + "%");
        lblTotal.setText("Total:" + controller.getTotal());

    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JRadioButton btnFeminino;
    private javax.swing.ButtonGroup btnGenero;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JRadioButton btnMasculino;
    private javax.swing.ButtonGroup btnRelatorios;
    private javax.swing.JComboBox<String> comboVip;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaResultadodosRelatorio;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblHomens;
    private javax.swing.JLabel lblMulheres;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPlatinum;
    private javax.swing.JLabel lblSilver;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVip;
    private javax.swing.JLabel lblVip1;
    private javax.swing.JTabbedPane panelPrincipal;
    private javax.swing.JPanel tabCadastro;
    private javax.swing.JPanel tabRelatorio;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
